***
# <font color=black size=10>Automatização de RC's</font>
***

# <font color=orange>1) Objetivo</font>
***

O objetivo é automatizar o processo de tomada de decisão de RC (Requisição de compra), analisando cada situação e propondo uma sugestão de resolução para cada caso.

# <font color=orange>2) Importando Bibliotecas e Dados</font>
***

In [54]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore') # ou warnings.filterwarnings(action='once')

In [55]:
# Importando as Requisições de Compras da ME5A

requisicoes = pd.read_excel('requisicoes_2.xlsx')
requisicoes

    Req. Compra  Item  Centro  Material    Texto Breve   Qtde  UM  Data doc.
0    1000000001    10       1  MATMM-01  Material - 01   1000  PÇ 2021-08-13
1    1000000001    20       1  MATMM-02  Material - 02   2500  PÇ 2021-08-13
2    1000000001    30       1  MATMM-03  Material - 03   3600  PÇ 2021-08-13
3    1000000001    40       1  MATMM-03  Material - 03   1500  PÇ 2021-08-13
4    1000000002    10       1  MATMM-05  Material - 05   2000  PÇ 2021-08-13
5    1000000002    20       1  MATMM-06  Material - 06    580  PÇ 2021-08-13
6    1000000002    30       1  MATMM-04  Material - 04    780  PÇ 2021-08-13
7    1000000004    10       1  MATMM-01  Material - 01   2500  PÇ 2021-08-13
8    1000000004    30       1  MATMM-07  Material - 07   5000  PÇ 2021-08-13
9    1000000004    40       1  MATMM-09  Material - 09     70  PÇ 2021-08-13
10   1000000005    10       1  MATMM-10  Material - 10    500  KG 2021-08-13
11   1000000005    20       1  MATMM-12  Material - 12   1500  KG 2021-08-13
12   1000000005    30       1  MATMM-12  Material - 12  10000  KG 2021-08-13
13   1000000006    20       1  MATMM-13  Material - 13    500  KG 2021-08-13
14   1000000006    30       1  MATMM-14  Material - 14    200  KG 2021-08-13
15   1000000007    20       1  MATMM-17  Material - 17  15000  KG 2021-08-13
16   1000000008    10       1  MATMM-18  Material - 18  20000  KG 2021-08-13
17   1000000008    20       1  MATMM-19  Material - 19   1000  MT 2021-08-13
18   1000000008    30       1  MATMM-20  Material - 20   2000  MT 2021-08-13
19   1000000009    10       1  MATMM-21  Material - 21    140  MT 2021-08-13
20   1000000010    10       1  MATMM-22  Material - 22    500  MT 2021-08-13
21   1000000011    10       1  MATMM-23  Material - 23    400  MT 2021-08-13
22   1000000016    10       1  MATMM-28  Material - 28    475  LT 2021-08-13
23   1000000016    20       1  MATMM-29  Material - 29   1900  LT 2021-08-13
24   1000000016    30       1  MATMM-30  Material - 30   2000  LT 2021-08-13
25   1000000016    40       1  MATMM-08  Material - 08   1000  PÇ 2021-08-13
26   1000000019    10       1  MATMM-08  Material - 08   1500  PÇ 2021-08-13
27   1000000020    10       1  MATMM-09  Material - 09   3000  PÇ 2021-08-13
28   1000000021    10       2  MATMM-31  Material - 10    100  PÇ 2021-08-14
29   1000000022    10       3  MATMM-32  Material - 11   1000  PÇ 2021-08-15
30   1000000023    10       4  MATMM-33  Material - 12   5000  PÇ 2021-08-16

In [56]:
# Importando histórico de compras por material da ME2M

compras = pd.read_excel('compras - 2.xlsx')
compras

,Pedido,Centro,Material,Data Doc.,Fornecedor,Qtde,Valor Unitario,UM,Montante,Frete
0,4500000043,1,MATMM-31,2021-08-15,FORN-01,10000,10.90,PÇ,109000.00,EXW
1,4500000042,2,MATMM-07,2021-08-14,FORN-15,1500,23.29,PÇ,34935.00,EXW
2,4500000041,1,MATMM-01,2021-08-12,FORN-01,1000,10.11,PÇ,10110.00,EXW
3,4500000040,1,MATMM-01,2021-08-07,FORN-02,2500,11.31,PÇ,28275.00,EXW
4,4500000039,1,MATMM-02,2021-08-02,FORN-03,3600,12.12,PÇ,43632.00,EXW
5,4500000038,1,MATMM-03,2021-07-28,FORN-04,1500,13.23,PÇ,19845.00,EXW
6,4500000037,1,MATMM-03,2021-07-23,FORN-05,1000,14.78,PÇ,14780.00,EXW
7,4500000036,1,MATMM-03,2021-07-18,FORN-06,2000,15.12,PÇ,30240.00,EXW
8,4500000035,1,MATMM-04,2021-07-13,FORN-07,580,16.11,PÇ,9343.80,EXW
9,4500000034,1,MATMM-04,2021-07-08,FORN-08,780,17.36,PÇ,13540.80,EXW
10,4500000033,1,MATMM-04,2021-07-03,FORN-09,1500,18.45,PÇ,27675.00,EXW
11,4500000032,1,MATMM-05,2021-06-28,FORN-10,2500,19.78,PÇ,49450.00,EXW
12,4500000031,1,MATMM-05,2021-06-23,FORN-11,3600,20.15,PÇ,72540.00,EXW
13,4500000030,1,MATMM-06,2021-06-18,FORN-12,5000,21.07,PÇ,105350.00,EXW
14,4500000029,1,MATMM-06,2021-06-13,FORN-13,70,22.09,PÇ,1546.30,EXW
15,4500000028,1,MATMM-07,2021-06-08,FORN-14,500,23.29,PÇ,11645.00,EXW
16,4500000027,1,MATMM-07,2021-06-03,FORN-15,1500,24.89,PÇ,37335.00,EXW
17,4500000026,1,MATMM-08,2021-05-29,FORN-16,10000,25.15,PÇ,251500.00,EXW
18,4500000025,1,MATMM-08,2021-05-24,FORN-17,1800,26.21,PÇ,47178.00,EXW
19,4500000024,1,MATMM-09,2021-05-19,FORN-18,500,27.31,PÇ,13655.00,EXW
20,4500000023,1,MATMM-09,2021-05-14,FORN-19,200,28.11,PÇ,5622.00,EXW
21,4500000022,1,MATMM-10,2021-05-09,FORN-20,50000,29.11,KG,1455500.00,EXW
22,4500000021,1,MATMM-11,2021-05-04,FORN-01,10000,30.11,KG,301100.00,CIF
23,4500000020,1,MATMM-12,2021-04-29,FORN-02,15000,31.11,KG,466650.00,CIF
24,4500000019,1,MATMM-12,2021-04-24,FORN-03,20000,32.11,KG,642200.00,CIF
25,4500000018,1,MATMM-13,2021-04-19,FORN-04,1000,33.11,KG,33110.00,CIF
26,4500000017,1,MATMM-14,2021-04-14,FORN-05,2000,34.45,KG,68900.00,CIF
27,4500000016,1,MATMM-15,2021-04-09,FORN-06,140,35.78,KG,5009.20,CIF
28,4500000015,1,MATMM-16,2021-04-04,FORN-07,500,36.15,KG,18075.00,CIF
29,4500000014,1,MATMM-17,2021-03-30,FORN-08,400,37.14,KG,14856.00,CIF
30,4500000013,1,MATMM-18,2021-03-25,FORN-09,300,38.18,KG,11454.00,CIF
31,4500000012,1,MATMM-19,2021-03-20,FORN-10,250,39.28,MT,9820.00,CIF
32,4500000011,1,MATMM-20,2021-03-15,FORN-11,340,40.72,MT,13844.80,CIF
33,4500000010,1,MATMM-21,2021-03-10,FORN-12,174,41.82,MT,7276.68,CIF
34,4500000009,1,MATMM-22,2021-03-05,FORN-13,475,42.74,MT,20301.50,CIF
35,4500000008,1,MATMM-23,2021-02-28,FORN-14,1900,43.45,MT,82555.00,CIF
36,4500000007,1,MATMM-24,2021-02-23,FORN-15,2000,44.54,MT,89080.00,CIF
37,4500000006,1,MATMM-25,2021-02-18,FORN-16,1000,45.37,LT,45370.00,CIF
38,4500000005,1,MATMM-26,2021-02-13,FORN-17,2500,46.84,LT,117100.00,CIF
39,4500000004,1,MATMM-27,2021-02-08,FORN-18,250,47.56,LT,11890.00,CIF
40,4500000003,1,MATMM-28,2021-02-03,FORN-19,1000,48.64,LT,48640.00,CIF
41,4500000002,1,MATMM-29,2021-01-29,FORN-20,1500,49.13,LT,73695.00,CIF
42,4500000001,1,MATMM-30,2021-01-24,FORN-12,3000,50.11,LT,150330.00,CIF

In [57]:
# Importando contratos por material da ME3M

contratos = pd.read_excel('contratos - 2.xlsx')
contratos

,Contrato,Centro,Material,Data Validade,Fornecedor,Valor Unitario,UM,Saldo,Frete
0,4600000011,1,MATMM-10,2021-12-31,FORN-20,29.11,PÇ,420321.12,EXW
1,4600000010,1,MATMM-12,2021-12-31,FORN-02,31.11,PÇ,420321.12,EXW
2,4600000010,1,MATMM-13,2020-07-31,FORN-04,33.11,PÇ,20316.45,EXW
3,4600000009,1,MATMM-14,2022-06-01,FORN-05,34.45,PÇ,86335.87,EXW
4,4600000008,1,MATMM-14,2020-12-31,FORN-05,34.45,PÇ,89652.45,EXW
5,4600000007,1,MATMM-14,2018-12-31,FORN-05,34.45,PÇ,7824.07,EXW
6,4600000006,1,MATMM-15,2021-03-30,FORN-06,35.78,KG,8224.25,CIF
7,4600000005,1,MATMM-16,2021-03-25,FORN-07,36.15,KG,7228.78,CIF
8,4600000004,1,MATMM-17,2021-03-20,FORN-08,37.14,MT,1200.12,CIF
9,4600000003,1,MATMM-18,2021-12-31,FORN-09,38.18,MT,12554.13,CIF
10,4600000002,1,MATMM-21,2022-03-15,FORN-12,41.82,MT,752.45,CIF
11,4600000001,1,MATMM-22,2022-06-06,FORN-13,42.74,MT,332552.12,CIF

In [58]:
# Importando tabela criada com as Fórmulas de reajuste por material 

condicoes = pd.read_excel('condicoes - 2.xlsx')
condicoes

    Material    Texto Breve  UM Grp Merc               Fórm. Reaj Fórm. Reaj.1
0   MATMM-01  Material - 01  PÇ    GM-01               100% Cobre       FR-001
1   MATMM-02  Material - 02  PÇ    GM-01               100% Cobre       FR-001
2   MATMM-03  Material - 03  PÇ    GM-02               100% Dolar       FR-002
3   MATMM-04  Material - 04  PÇ    GM-02               100% Dolar       FR-002
4   MATMM-05  Material - 05  PÇ    GM-03             100% Estanho       FR-003
5   MATMM-06  Material - 06  PÇ    GM-03             100% Estanho       FR-003
6   MATMM-07  Material - 07  PÇ    GM-03             100% Estanho       FR-003
7   MATMM-08  Material - 08  PÇ    GM-04               100% IGP-M       FR-004
8   MATMM-09  Material - 09  PÇ    GM-04               100% IGP-M       FR-004
9   MATMM-10  Material - 10  KG    GM-04               100% IGP-M       FR-004
10  MATMM-11  Material - 11  KG    GM-05            100% Petroleo       FR-005
11  MATMM-12  Material - 12  KG    GM-05            100% Petroleo       FR-005
12  MATMM-13  Material - 13  KG    GM-05            100% Petroleo       FR-005
13  MATMM-14  Material - 14  KG    GM-06    50% Dolar + 50% IGP-M       FR-006
14  MATMM-15  Material - 15  KG    GM-06    50% Dolar + 50% IGP-M       FR-006
15  MATMM-16  Material - 16  KG    GM-06    50% Dolar + 50% IGP-M       FR-006
16  MATMM-17  Material - 17  KG    GM-07    50% Dolar + 50% IGP-M       FR-006
17  MATMM-18  Material - 18  KG    GM-07    50% Dolar + 50% IGP-M       FR-006
18  MATMM-19  Material - 19  MT    GM-07    50% Dolar + 50% IGP-M       FR-006
19  MATMM-20  Material - 20  MT    GM-08  50% Petroleo + 50% Soja       FR-007
20  MATMM-21  Material - 21  MT    GM-09               100% Cobre       FR-001
21  MATMM-22  Material - 22  MT    GM-10             100% Estanho       FR-003
22  MATMM-23  Material - 23  MT    GM-11               100% Dolar       FR-002
23  MATMM-24  Material - 24  MT    GM-12  50% Petroleo + 50% Soja       FR-007
24  MATMM-25  Material - 25  LT    GM-12  50% Petroleo + 50% Soja       FR-007
25  MATMM-26  Material - 26  LT    GM-12  50% Petroleo + 50% Soja       FR-007
26  MATMM-27  Material - 27  LT    GM-12    50% Dolar + 50% IGP-M       FR-006
27  MATMM-28  Material - 28  LT    GM-12    50% Dolar + 50% IGP-M       FR-006
28  MATMM-29  Material - 29  LT    GM-12    50% Dolar + 50% IGP-M       FR-006
29  MATMM-30  Material - 30  LT    GM-12    50% Dolar + 50% IGP-M       FR-006
30  MATMM-31  Material - 31  LT    GM-12    50% Dolar + 50% IGP-M       FR-006

In [59]:
# Importando tabela com os drivers de preço de cada material. Tabela com todos os índices já acumulados.

## O ideal é coletar os dados diretamente da internet, mas, foi coletado e tratado em excel apenas para agilidade na demonstração.

indices = pd.read_excel('indices - 2.xlsx')
indices

,Data,Dolar 1,Dolar 2,Dolar 3,Dolar F,IGPM 1,IGPM 2,IGPM 3,IGPM F,Petro 1,...,Soja 3,Soja F,Cobre 1,Cobre 2,Cobre 3,Cobre F,Estanho 1,Estanho 2,Estanho 3,Estanho F
0,2021-01-01,-0.012000,0.999880,-4.190823,-4.179325,0.083226,1.000832,17.208140,17.110673,0.030833,...,2.571885,2.554451,0.051833,1.000518,15.999186,15.939091,-0.017333,0.999827,-3.249929,-3.233156
1,2021-01-02,-0.027833,0.999722,-4.179325,-4.152647,0.083226,1.000832,17.110673,17.013288,0.034333,...,2.554451,2.533602,0.055333,1.000553,15.939091,15.874974,-0.020833,0.999792,-3.233156,-3.212992
2,2021-01-03,-0.031333,0.999687,-4.152647,-4.122606,0.083226,1.000832,17.013288,16.915984,0.037833,...,2.533602,2.509171,0.058833,1.000588,15.874974,15.806840,-0.024333,0.999757,-3.212992,-3.189435
3,2021-01-04,-0.034833,0.999652,-4.122606,-4.089197,0.083226,1.000832,16.915984,16.818761,0.041333,...,2.509171,2.481159,0.062333,1.000623,15.806840,15.734699,-0.027833,0.999722,-3.189435,-3.162481
4,2021-01-05,-0.044500,0.999555,-4.089197,-4.046498,0.083226,1.000832,16.818761,16.721618,0.044833,...,2.481159,2.449571,0.065833,1.000658,15.734699,15.658557,-0.031333,0.999687,-3.162481,-3.132130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2021-09-05,-0.066100,0.999339,-1.188287,-1.260716,0.000000,1.000000,0.528309,0.528309,-0.073528,...,-0.468639,-0.499826,0.121833,1.001218,1.931368,2.059122,-0.034833,0.999652,-0.468301,-0.506455
248,2021-09-06,-0.073300,0.999267,-1.260716,-1.340201,0.000000,1.000000,0.528309,0.528309,-0.079944,...,-0.499826,-0.534485,0.125333,1.001253,2.059122,2.190609,-0.038333,0.999617,-0.506455,-0.548076
249,2021-09-07,-0.080500,0.999195,-1.340201,-1.426725,0.000000,1.000000,0.528309,0.528309,-0.086361,...,-0.534485,-0.572614,0.128833,1.001288,2.190609,2.325841,-0.041833,0.999582,-0.548076,-0.593161
250,2021-09-08,-0.087700,0.999123,-1.426725,-1.520271,0.000000,1.000000,0.528309,0.528309,-0.092778,...,-0.572614,-0.614207,0.132333,1.001323,2.325841,2.464833,-0.045333,0.999547,-0.593161,-0.641705
251,2021-09-09,-0.094900,0.999051,-1.520271,0.000000,0.000000,1.000000,0.528309,0.000000,-0.099194,...,-0.614207,0.000000,0.135833,1.001358,2.464833,0.000000,-0.048833,0.999512,-0.641705,0.000000

# <font color=orange>3) Aplicando as fórmulas de reajuste para atualização dos Preços</font>
***

In [60]:
# Selecionando tabela de compras e selecionando o último pedido para cada código de material

df_compras = compras[{'Pedido', 'Material', 'Data Doc.', 'Fornecedor', 'Valor Unitario', 'UM', 'Frete'}]
ultimo_valor = df_compras.groupby(["Material"])['Pedido'].max().reset_index()
df_compras = pd.merge(ultimo_valor, df_compras, on=['Material'], how='left')


## Função para excluir pedidos anteriores ao último de cada material

def f(row):
    if row['Pedido_x'] == row['Pedido_y']:
        val = 0
    elif row['Pedido_x'] > row['Pedido_y']:
        val = 1
    else:
        val = -1
    return val
df_compras["retirar"] = df_compras.apply(f, axis=1)


### Ajustando tabela para melhor visualização dos dados

df_compras= df_compras.rename(columns={'Pedido_x': 'Pedido'})
df_compras = df_compras.query('retirar==0')
df_compras = df_compras.drop(columns=['Pedido_y', 'retirar'])
df_compras

    Material      Pedido Fornecedor  Valor Unitario  UM Frete  Data Doc.
0   MATMM-01  4500000041    FORN-01           10.11  PÇ   EXW 2021-08-12
2   MATMM-02  4500000039    FORN-03           12.12  PÇ   EXW 2021-08-02
3   MATMM-03  4500000038    FORN-04           13.23  PÇ   EXW 2021-07-28
6   MATMM-04  4500000035    FORN-07           16.11  PÇ   EXW 2021-07-13
9   MATMM-05  4500000032    FORN-10           19.78  PÇ   EXW 2021-06-28
11  MATMM-06  4500000030    FORN-12           21.07  PÇ   EXW 2021-06-18
13  MATMM-07  4500000042    FORN-15           23.29  PÇ   EXW 2021-08-14
16  MATMM-08  4500000026    FORN-16           25.15  PÇ   EXW 2021-05-29
18  MATMM-09  4500000024    FORN-18           27.31  PÇ   EXW 2021-05-19
20  MATMM-10  4500000022    FORN-20           29.11  KG   EXW 2021-05-09
21  MATMM-11  4500000021    FORN-01           30.11  KG   CIF 2021-05-04
22  MATMM-12  4500000020    FORN-02           31.11  KG   CIF 2021-04-29
24  MATMM-13  4500000018    FORN-04           33.11  KG   CIF 2021-04-19
25  MATMM-14  4500000017    FORN-05           34.45  KG   CIF 2021-04-14
26  MATMM-15  4500000016    FORN-06           35.78  KG   CIF 2021-04-09
27  MATMM-16  4500000015    FORN-07           36.15  KG   CIF 2021-04-04
28  MATMM-17  4500000014    FORN-08           37.14  KG   CIF 2021-03-30
29  MATMM-18  4500000013    FORN-09           38.18  KG   CIF 2021-03-25
30  MATMM-19  4500000012    FORN-10           39.28  MT   CIF 2021-03-20
31  MATMM-20  4500000011    FORN-11           40.72  MT   CIF 2021-03-15
32  MATMM-21  4500000010    FORN-12           41.82  MT   CIF 2021-03-10
33  MATMM-22  4500000009    FORN-13           42.74  MT   CIF 2021-03-05
34  MATMM-23  4500000008    FORN-14           43.45  MT   CIF 2021-02-28
35  MATMM-24  4500000007    FORN-15           44.54  MT   CIF 2021-02-23
36  MATMM-25  4500000006    FORN-16           45.37  LT   CIF 2021-02-18
37  MATMM-26  4500000005    FORN-17           46.84  LT   CIF 2021-02-13
38  MATMM-27  4500000004    FORN-18           47.56  LT   CIF 2021-02-08
39  MATMM-28  4500000003    FORN-19           48.64  LT   CIF 2021-02-03
40  MATMM-29  4500000002    FORN-20           49.13  LT   CIF 2021-01-29
41  MATMM-30  4500000001    FORN-12           50.11  LT   CIF 2021-01-24
42  MATMM-31  4500000043    FORN-01           10.90  PÇ   EXW 2021-08-15

In [61]:
# Unificando os indicadores e a fórmula de reajuste dos materiais

df_preco_novo = df_compras[{'Material', 'Pedido', 'Data Doc.', 'Valor Unitario'}]
df_indices = indices[{'Data', 'Dolar F', 'IGPM F', 'Petro F', 'Soja F', 'Cobre F', 'Estanho F'}]
df_indices= df_indices.rename(columns={'Data': 'Data Doc.'})
df_preco_novo = pd.merge(df_preco_novo, df_indices, on=['Data Doc.'], how='left')
df_preco_novo = pd.merge(df_preco_novo, condicoes, on=['Material'], how='left')
df_preco_novo = df_preco_novo.drop(columns=['Grp Merc', 'Fórm. Reaj', 'Texto Breve', 'UM'])
df_preco_novo= df_preco_novo.rename(columns={'Fórm. Reaj.1': 'form_reaj'})
df_preco_novo

,Data Doc.,Material,Valor Unitario,Pedido,Cobre F,Estanho F,IGPM F,Soja F,Dolar F,Petro F,form_reaj
0,2021-08-12,MATMM-01,10.11,4500000041,0.260726,-0.062487,0.093029,0.187181,-0.284430,0.134560,FR-001
1,2021-08-02,MATMM-02,12.12,4500000039,0.905081,0.245041,0.403750,0.584457,-0.763047,0.303866,FR-001
2,2021-07-28,MATMM-03,13.23,4500000038,1.096104,0.382117,0.580082,0.693637,-0.575182,0.441835,FR-002
3,2021-07-13,MATMM-04,16.11,4500000035,2.481757,0.024148,1.152389,1.206020,-0.807149,-0.235939,FR-002
4,2021-06-28,MATMM-05,19.78,4500000032,3.281433,0.500287,1.678804,1.746100,-0.843637,-0.299673,FR-003
5,2021-06-18,MATMM-06,21.07,4500000030,3.338517,0.201508,1.882344,1.601154,-0.971176,0.072973,FR-003
6,2021-08-14,MATMM-07,23.29,4500000042,0.090333,-0.024333,0.031000,0.065868,-0.102100,0.048333,FR-003
7,2021-05-29,MATMM-08,25.15,4500000026,4.396811,-0.718852,2.520391,1.872835,-0.778358,0.122233,FR-004
8,2021-05-19,MATMM-09,27.31,4500000024,6.305246,-1.116092,3.884404,1.668043,-1.153312,0.430330,FR-004
9,2021-05-09,MATMM-10,29.11,4500000022,7.029544,-1.313852,5.266565,1.628858,-1.837715,0.480501,FR-004
10,2021-05-04,MATMM-11,30.11,4500000021,7.194649,-1.380291,5.964527,1.856880,-1.829887,0.491031,FR-005
11,2021-04-29,MATMM-12,31.11,4500000020,7.483795,-1.500221,6.579845,1.996159,-1.767068,0.734119,FR-005
12,2021-04-19,MATMM-13,33.11,4500000018,8.439721,-1.749011,7.117513,2.382687,-2.091577,1.367250,FR-005
13,2021-04-14,MATMM-14,34.45,4500000017,8.778112,-1.851477,7.387364,1.362105,-2.010150,1.155400,FR-006
14,2021-04-09,MATMM-15,35.78,4500000016,9.113743,-1.705173,7.657894,1.372728,-1.790293,1.032387,FR-006
15,2021-04-04,MATMM-16,36.15,4500000015,9.377688,-1.501863,7.929106,1.617948,-1.656000,1.116413,FR-006
16,2021-03-30,MATMM-17,37.14,4500000014,9.546416,-1.384266,8.249132,1.774705,-1.716163,1.343285,FR-006
17,2021-03-25,MATMM-18,38.18,4500000013,9.841905,-1.506018,8.763417,1.782829,-1.904397,1.315070,FR-006
18,2021-03-20,MATMM-19,39.28,4500000012,10.377510,-1.677443,9.280145,1.605676,-2.006701,1.525289,FR-006
19,2021-03-15,MATMM-20,40.72,4500000011,10.818803,-1.762463,9.799329,1.690178,-2.344274,0.711443,FR-007
20,2021-03-10,MATMM-21,41.82,4500000010,11.164619,-1.558630,10.320979,1.918338,-2.736709,0.606411,FR-001
21,2021-03-05,MATMM-22,42.74,4500000009,11.476414,-1.372271,10.845107,2.147009,-2.951732,0.756379,FR-003
22,2021-02-28,MATMM-23,43.45,4500000008,11.706988,-1.272124,11.371725,2.286686,-2.941550,0.964780,FR-002
23,2021-02-23,MATMM-24,44.54,4500000007,11.840355,-1.448076,11.875797,2.523522,-3.114527,1.085322,FR-007
24,2021-02-18,MATMM-25,45.37,4500000006,12.330287,-1.602378,12.382150,1.701674,-3.266220,0.960521,FR-007
25,2021-02-13,MATMM-26,46.84,4500000005,12.838562,-1.670418,12.890795,1.595609,-3.333109,0.855563,FR-007
26,2021-02-08,MATMM-27,47.56,4500000004,13.250081,-1.836455,13.401742,1.747052,-3.082322,1.064828,FR-006
27,2021-02-03,MATMM-28,48.64,4500000003,13.587589,-2.230113,13.915001,1.957502,-2.915833,1.291585,FR-006
28,2021-01-29,MATMM-29,49.13,4500000002,13.922119,-2.536888,14.414278,2.079229,-2.834093,1.483339,FR-006
29,2021-01-24,MATMM-30,50.11,4500000001,14.157752,-2.757605,14.891182,1.953201,-3.054137,1.586386,FR-006
30,2021-08-15,MATMM-31,10.90,4500000043,0.142213,-0.052160,0.062010,0.058864,-0.114088,0.041330,FR-006

In [62]:
# Aplicando a fórmula de reajuste com base na coluna "form_reaj" e adicionando coluna "preco_previsto"

fr001 = df_preco_novo.query('form_reaj=="FR-001"')
fr001["preco_previsto"] = ((fr001["Valor Unitario"] * 
fr001["Cobre F"])/100 + 
fr001["Valor Unitario"]).round(2)

fr002 = df_preco_novo.query('form_reaj=="FR-002"')
fr002["preco_previsto"] = ((fr002["Valor Unitario"] * 
fr002["Dolar F"])/100 + 
fr002["Valor Unitario"]).round(2)

fr003 = df_preco_novo.query('form_reaj=="FR-003"')
fr003["preco_previsto"] = ((fr003["Valor Unitario"] * 
fr003["Estanho F"])/100 + 
fr003["Valor Unitario"]).round(2)

fr004 = df_preco_novo.query('form_reaj=="FR-004"')
fr004["preco_previsto"] = ((fr004["Valor Unitario"] * 
fr004["IGPM F"])/100 + 
fr004["Valor Unitario"]).round(2)

fr005 = df_preco_novo.query('form_reaj=="FR-005"')
fr005["preco_previsto"] = ((fr005["Valor Unitario"] * 
fr005["Petro F"])/100 + 
fr005["Valor Unitario"]).round(2)

fr006 = df_preco_novo.query('form_reaj=="FR-006"')
fr006["preco_previsto"] = (
                           ((fr006["Valor Unitario"] * fr006["Dolar F"])/100*0.5)+
                           ((fr006["Valor Unitario"] * fr006["IGPM F"])/100*0.5)+
                             fr006["Valor Unitario"]
                        ).round(2)

fr007 = df_preco_novo.query('form_reaj=="FR-007"')
fr007["preco_previsto"] = (
                           ((fr007["Valor Unitario"] * fr007["Petro F"])/100*0.5)+
                           ((fr007["Valor Unitario"] * fr007["Soja F"])/100*0.5)+
                             fr007["Valor Unitario"]
                        ).round(2)

df_preco_previsto = pd.concat([fr001,fr002,fr003,fr004,fr005,fr006,fr007])
df_preco_previsto = df_preco_previsto[['Material', 'Pedido', 'Valor Unitario', 'preco_previsto']]
df_preco_previsto = df_preco_previsto.sort_values(by='Material')
df_preco_previsto.tail(15)

    Material      Pedido  Valor Unitario  preco_previsto
16  MATMM-17  4500000014           37.14           38.35
17  MATMM-18  4500000013           38.18           39.49
18  MATMM-19  4500000012           39.28           40.71
19  MATMM-20  4500000011           40.72           41.21
20  MATMM-21  4500000010           41.82           46.49
21  MATMM-22  4500000009           42.74           42.15
22  MATMM-23  4500000008           43.45           42.17
23  MATMM-24  4500000007           44.54           45.34
24  MATMM-25  4500000006           45.37           45.97
25  MATMM-26  4500000005           46.84           47.41
26  MATMM-27  4500000004           47.56           50.01
27  MATMM-28  4500000003           48.64           51.31
28  MATMM-29  4500000002           49.13           51.97
29  MATMM-30  4500000001           50.11           53.08
30  MATMM-31  4500000043           10.90           10.90

# <font color=orange>4) Unificando todas as informações em um Dataset</font>
***

In [63]:
# Calculando a diferença entre "Preço pago última compra" e o "Preço Previsto" 
## Objetivo é verificar se a previsão é de aumento ou queda no preço.

diferenca = df_preco_previsto[{'Material', 'Pedido', 'Valor Unitario', 'preco_previsto'}]
diferenca= diferenca.rename(columns={'Valor Unitario': 'ultimo_preco'})
diferenca = diferenca[['Material', 'Pedido', 'ultimo_preco', 'preco_previsto']]
diferenca["diferenca"] = ((diferenca["preco_previsto"] - 
                         diferenca["ultimo_preco"]
                        )).round(2)
diferenca

    Material      Pedido  ultimo_preco  preco_previsto  diferenca
0   MATMM-01  4500000041         10.11           10.14       0.03
1   MATMM-02  4500000039         12.12           12.23       0.11
2   MATMM-03  4500000038         13.23           13.15      -0.08
3   MATMM-04  4500000035         16.11           15.98      -0.13
4   MATMM-05  4500000032         19.78           19.88       0.10
5   MATMM-06  4500000030         21.07           21.11       0.04
6   MATMM-07  4500000042         23.29           23.28      -0.01
7   MATMM-08  4500000026         25.15           25.78       0.63
8   MATMM-09  4500000024         27.31           28.37       1.06
9   MATMM-10  4500000022         29.11           30.64       1.53
10  MATMM-11  4500000021         30.11           30.26       0.15
11  MATMM-12  4500000020         31.11           31.34       0.23
12  MATMM-13  4500000018         33.11           33.56       0.45
13  MATMM-14  4500000017         34.45           35.38       0.93
14  MATMM-15  4500000016         35.78           36.83       1.05
15  MATMM-16  4500000015         36.15           37.28       1.13
16  MATMM-17  4500000014         37.14           38.35       1.21
17  MATMM-18  4500000013         38.18           39.49       1.31
18  MATMM-19  4500000012         39.28           40.71       1.43
19  MATMM-20  4500000011         40.72           41.21       0.49
20  MATMM-21  4500000010         41.82           46.49       4.67
21  MATMM-22  4500000009         42.74           42.15      -0.59
22  MATMM-23  4500000008         43.45           42.17      -1.28
23  MATMM-24  4500000007         44.54           45.34       0.80
24  MATMM-25  4500000006         45.37           45.97       0.60
25  MATMM-26  4500000005         46.84           47.41       0.57
26  MATMM-27  4500000004         47.56           50.01       2.45
27  MATMM-28  4500000003         48.64           51.31       2.67
28  MATMM-29  4500000002         49.13           51.97       2.84
29  MATMM-30  4500000001         50.11           53.08       2.97
30  MATMM-31  4500000043         10.90           10.90       0.00

In [64]:
# Criando dataset com as informações, por RC

df_rcs = requisicoes[{'Req. Compra', 'Material', 'Qtde', 'UM', 'Data doc.'}]

df_rcs = pd.merge(df_rcs, diferenca, on=['Material'], how='left')
df_rcs = df_rcs.drop(columns=['Data doc.','Pedido'])
df_rcs["montante"] = ((df_rcs["diferenca"] * 
                         df_rcs["Qtde"]
                        )).round(2)
df_rcs = df_rcs[['Req. Compra', 'Material', 'Qtde', 'UM', 'ultimo_preco', 'preco_previsto', 'diferenca', 'montante']]
df_rcs

,Req. Compra,Material,Qtde,UM,ultimo_preco,preco_previsto,diferenca,montante
0,1000000001,MATMM-01,1000,PÇ,10.11,10.14,0.03,30.00
1,1000000001,MATMM-02,2500,PÇ,12.12,12.23,0.11,275.00
2,1000000001,MATMM-03,3600,PÇ,13.23,13.15,-0.08,-288.00
3,1000000001,MATMM-03,1500,PÇ,13.23,13.15,-0.08,-120.00
4,1000000002,MATMM-05,2000,PÇ,19.78,19.88,0.10,200.00
5,1000000002,MATMM-06,580,PÇ,21.07,21.11,0.04,23.20
6,1000000002,MATMM-04,780,PÇ,16.11,15.98,-0.13,-101.40
7,1000000004,MATMM-01,2500,PÇ,10.11,10.14,0.03,75.00
8,1000000004,MATMM-07,5000,PÇ,23.29,23.28,-0.01,-50.00
9,1000000004,MATMM-09,70,PÇ,27.31,28.37,1.06,74.20
10,1000000005,MATMM-10,500,KG,29.11,30.64,1.53,765.00
11,1000000005,MATMM-12,1500,KG,31.11,31.34,0.23,345.00
12,1000000005,MATMM-12,10000,KG,31.11,31.34,0.23,2300.00
13,1000000006,MATMM-13,500,KG,33.11,33.56,0.45,225.00
14,1000000006,MATMM-14,200,KG,34.45,35.38,0.93,186.00
15,1000000007,MATMM-17,15000,KG,37.14,38.35,1.21,18150.00
16,1000000008,MATMM-18,20000,KG,38.18,39.49,1.31,26200.00
17,1000000008,MATMM-19,1000,MT,39.28,40.71,1.43,1430.00
18,1000000008,MATMM-20,2000,MT,40.72,41.21,0.49,980.00
19,1000000009,MATMM-21,140,MT,41.82,46.49,4.67,653.80
20,1000000010,MATMM-22,500,MT,42.74,42.15,-0.59,-295.00
21,1000000011,MATMM-23,400,MT,43.45,42.17,-1.28,-512.00
22,1000000016,MATMM-28,475,LT,48.64,51.31,2.67,1268.25
23,1000000016,MATMM-29,1900,LT,49.13,51.97,2.84,5396.00
24,1000000016,MATMM-30,2000,LT,50.11,53.08,2.97,5940.00
25,1000000016,MATMM-08,1000,PÇ,25.15,25.78,0.63,630.00
26,1000000019,MATMM-08,1500,PÇ,25.15,25.78,0.63,945.00
27,1000000020,MATMM-09,3000,PÇ,27.31,28.37,1.06,3180.00
28,1000000021,MATMM-31,100,PÇ,10.90,10.90,0.00,0.00
29,1000000022,MATMM-32,1000,PÇ,NaN,NaN,NaN,NaN
30,1000000023,MATMM-33,5000,PÇ,NaN,NaN,NaN,NaN

# <font color=orange>5) Verificando quais RC's possuem contratos com possibilidade de aumento de preço</font>
***

In [65]:
df_contratos = contratos[{'Contrato', 'Material', 'Data Validade', 'Saldo', 'Fornecedor'}]
ultimo_contrato = df_contratos.groupby(["Material"])['Contrato'].max().reset_index()
df_contratos = pd.merge(df_contratos, ultimo_contrato, on=['Material'], how='left')

def f(row):
    if row['Contrato_x'] == row['Contrato_y']:
        val = 0
    elif row['Contrato_x'] > row['Contrato_y']:
        val = 1
    else:
        val = -1
    return val  

df_contratos["retirar"] = df_contratos.apply(f, axis=1)
df_contratos= df_contratos.rename(columns={'Contrato_x': 'Contrato'})
df_contratos = df_contratos.query('retirar==0')
df_contratos = df_contratos.drop(columns=['Contrato_y', 'retirar'])
df_contratos

      Contrato Fornecedor Data Validade  Material      Saldo
0   4600000011    FORN-20    2021-12-31  MATMM-10  420321.12
1   4600000010    FORN-02    2021-12-31  MATMM-12  420321.12
2   4600000010    FORN-04    2020-07-31  MATMM-13   20316.45
3   4600000009    FORN-05    2022-06-01  MATMM-14   86335.87
6   4600000006    FORN-06    2021-03-30  MATMM-15    8224.25
7   4600000005    FORN-07    2021-03-25  MATMM-16    7228.78
8   4600000004    FORN-08    2021-03-20  MATMM-17    1200.12
9   4600000003    FORN-09    2021-12-31  MATMM-18   12554.13
10  4600000002    FORN-12    2022-03-15  MATMM-21     752.45
11  4600000001    FORN-13    2022-06-06  MATMM-22  332552.12

In [66]:
# Verificando RC's que possuam contratos, saldo e período de vigência corretos

rcs_1 = df_contratos
rcs_1 = pd.merge(df_rcs, rcs_1, on=['Material'], how='right')
rcs_1["total_previsto"] = ((rcs_1["Qtde"] * 
                         rcs_1["ultimo_preco"]
                        )).round(2)
rcs_1["saldo_novo"] = ((rcs_1["Saldo"] - 
                         rcs_1["total_previsto"]
                        )).round(2)
rcs_1 = rcs_1.query('montante>=0')
rcs_1 = rcs_1.query('saldo_novo>=0')
rcs_1

,Req. Compra,Material,Qtde,UM,ultimo_preco,preco_previsto,diferenca,montante,Contrato,Fornecedor,Data Validade,Saldo,total_previsto,saldo_novo
0,1.000000e+09,MATMM-10,500.0,KG,29.11,30.64,1.53,765.0,4600000011,FORN-20,2021-12-31,420321.12,14555.0,405766.12
1,1.000000e+09,MATMM-12,1500.0,KG,31.11,31.34,0.23,345.0,4600000010,FORN-02,2021-12-31,420321.12,46665.0,373656.12
2,1.000000e+09,MATMM-12,10000.0,KG,31.11,31.34,0.23,2300.0,4600000010,FORN-02,2021-12-31,420321.12,311100.0,109221.12
3,1.000000e+09,MATMM-13,500.0,KG,33.11,33.56,0.45,225.0,4600000010,FORN-04,2020-07-31,20316.45,16555.0,3761.45
4,1.000000e+09,MATMM-14,200.0,KG,34.45,35.38,0.93,186.0,4600000009,FORN-05,2022-06-01,86335.87,6890.0,79445.87

In [67]:
# Verificando RC's que possuam contratos, período de vigência corretos, mas que não tem saldo.

rcs_2 = df_contratos
rcs_2 = pd.merge(df_rcs, rcs_2, on=['Material'], how='right')
rcs_2["total_previsto"] = ((rcs_2["Qtde"] * 
                         rcs_2["ultimo_preco"]
                        )).round(2)
rcs_2["saldo_novo"] = ((rcs_2["Saldo"] - 
                         rcs_2["total_previsto"]
                        )).round(2)
rcs_2 = rcs_2.query('montante>=0')
rcs_2 = rcs_2.query('saldo_novo<0')
rcs_2

,Req. Compra,Material,Qtde,UM,ultimo_preco,preco_previsto,diferenca,montante,Contrato,Fornecedor,Data Validade,Saldo,total_previsto,saldo_novo
7,1.000000e+09,MATMM-17,15000.0,KG,37.14,38.35,1.21,18150.0,4600000004,FORN-08,2021-03-20,1200.12,557100.0,-555899.88
8,1.000000e+09,MATMM-18,20000.0,KG,38.18,39.49,1.31,26200.0,4600000003,FORN-09,2021-12-31,12554.13,763600.0,-751045.87
9,1.000000e+09,MATMM-21,140.0,MT,41.82,46.49,4.67,653.8,4600000002,FORN-12,2022-03-15,752.45,5854.8,-5102.35

# <font color=orange>6) RC's que possuem contratos, mas que poderiam ter redução de preços</font>
***

In [68]:
rcs_3 = df_contratos
rcs_3 = pd.merge(df_rcs, rcs_3, on=['Material'], how='right')
rcs_3["total_previsto"] = ((rcs_3["Qtde"] * 
                         rcs_3["ultimo_preco"]
                        )).round(2)
rcs_3["saldo_novo"] = ((rcs_3["Saldo"] - 
                         rcs_3["total_previsto"]
                        )).round(2)
rcs_3 = rcs_3.query('montante<0')
rcs_3

,Req. Compra,Material,Qtde,UM,ultimo_preco,preco_previsto,diferenca,montante,Contrato,Fornecedor,Data Validade,Saldo,total_previsto,saldo_novo
10,1.000000e+09,MATMM-22,500.0,MT,42.74,42.15,-0.59,-295.0,4600000001,FORN-13,2022-06-06,332552.12,21370.0,311182.12

# <font color=orange>7) RC's que não possuem contratos, mas que estão prontas para emissão de pedido</font>
***

In [69]:
# RC's que estão sem contrato, mas que tem previsão de alta nos preços. Portanto melhor indicação de comprar conforme último pedido.

rcs_4 = contratos[{'Contrato', 'Material', 'Data Validade', 'Saldo'}]
rcs_4 = pd.merge(df_rcs, rcs_4, on=['Material'], how='left')
rcs_4 = rcs_4.query('montante>=0')
rcs_4.fillna("Fica", inplace = True)
rcs_4 = rcs_4.query('Saldo=="Fica"')
rcs_4 = rcs_4[['Req. Compra', 'Material', 'Qtde', 'UM', 'ultimo_preco', 'preco_previsto', 'diferenca', 'montante']]
rcs_4 = rcs_4.sort_values(by='Req. Compra')
rcs_4

,Req. Compra,Material,Qtde,UM,ultimo_preco,preco_previsto,diferenca,montante
0,1000000001,MATMM-01,1000,PÇ,10.11,10.14,0.03,30.00
1,1000000001,MATMM-02,2500,PÇ,12.12,12.23,0.11,275.00
4,1000000002,MATMM-05,2000,PÇ,19.78,19.88,0.10,200.00
5,1000000002,MATMM-06,580,PÇ,21.07,21.11,0.04,23.20
7,1000000004,MATMM-01,2500,PÇ,10.11,10.14,0.03,75.00
9,1000000004,MATMM-09,70,PÇ,27.31,28.37,1.06,74.20
19,1000000008,MATMM-19,1000,MT,39.28,40.71,1.43,1430.00
20,1000000008,MATMM-20,2000,MT,40.72,41.21,0.49,980.00
24,1000000016,MATMM-28,475,LT,48.64,51.31,2.67,1268.25
25,1000000016,MATMM-29,1900,LT,49.13,51.97,2.84,5396.00
26,1000000016,MATMM-30,2000,LT,50.11,53.08,2.97,5940.00
27,1000000016,MATMM-08,1000,PÇ,25.15,25.78,0.63,630.00
28,1000000019,MATMM-08,1500,PÇ,25.15,25.78,0.63,945.00
29,1000000020,MATMM-09,3000,PÇ,27.31,28.37,1.06,3180.00
30,1000000021,MATMM-31,100,PÇ,10.90,10.90,0.00,0.00

# <font color=orange>8)  RC's que não possuem contratos, que devem ser designadas para cotação</font>
***

In [70]:
# RC's que estão sem contrato e que tem previsão de queda de preços. Designadas para abertura de cotação

rcs_5 = contratos[{'Contrato', 'Material', 'Data Validade', 'Saldo'}]
rcs_5 = pd.merge(df_rcs, rcs_5, on=['Material'], how='left')
rcs_5 = rcs_5.query('montante<0')
rcs_5.fillna("Fica", inplace = True)
rcs_5 = rcs_5.query('Saldo=="Fica"')
rcs_5 = rcs_5[['Req. Compra', 'Material', 'Qtde', 'UM', 'ultimo_preco', 'preco_previsto', 'diferenca', 'montante']]
rcs_5 = rcs_5.sort_values(by='Req. Compra')
rcs_5

,Req. Compra,Material,Qtde,UM,ultimo_preco,preco_previsto,diferenca,montante
2,1000000001,MATMM-03,3600,PÇ,13.23,13.15,-0.08,-288.0
3,1000000001,MATMM-03,1500,PÇ,13.23,13.15,-0.08,-120.0
6,1000000002,MATMM-04,780,PÇ,16.11,15.98,-0.13,-101.4
8,1000000004,MATMM-07,5000,PÇ,23.29,23.28,-0.01,-50.0
23,1000000011,MATMM-23,400,MT,43.45,42.17,-1.28,-512.0

# <font color=orange>9) RC's que não possuem histórico de compras</font>
***

In [71]:
# RC's que não possuem histórico de compras e que portanto devem ser enviadas para cotação.

rcs_6 = requisicoes[{'Req. Compra', 'Item', 'Material', 'Data doc.', 'Qtde', 'UM'}]
rcs_6 = pd.merge(df_compras, rcs_6, on=['Material'], how='outer')
rcs_6.fillna("Fica", inplace = True)
rcs_6 = rcs_6.query('Frete=="Fica"')


rcs_6= rcs_6.rename(columns={'UM_y': 'UM'})
rcs_6 = rcs_6.drop(columns=['Pedido', 'Frete', 'Fornecedor','Valor Unitario', 'UM_x', 'Data Doc.'])

rcs_6 = rcs_6[['Req. Compra', 'Material', 'Qtde', 'UM', 'Item']]
rcs_6 = rcs_6.sort_values(by='Req. Compra')

rcs_6

   Req. Compra  Material  Qtde  UM Item
36       1e+09  MATMM-32  1000  PÇ   10
37       1e+09  MATMM-33  5000  PÇ   10

# <font color=orange>10) RC's que devem ser pedidas via contrato ou conforme última compra</font>
***

In [72]:
rcs_1 = rcs_1[{'Req. Compra', 'Material', 'Qtde', 'UM', 'ultimo_preco'}]
rcs_4 = rcs_4[{'Req. Compra', 'Material', 'Qtde', 'UM', 'ultimo_preco'}]
fazer_pedido = pd.concat([rcs_1,rcs_4])
fazer_pedido = fazer_pedido[['Req. Compra', 'Material', 'ultimo_preco', 'Qtde', 'UM']]
fazer_pedido = fazer_pedido.sort_values(by='Req. Compra')
fazer_pedido

     Req. Compra  Material  ultimo_preco     Qtde  UM
1   1.000000e+09  MATMM-02         12.12   2500.0  PÇ
0   1.000000e+09  MATMM-01         10.11   1000.0  PÇ
5   1.000000e+09  MATMM-06         21.07    580.0  PÇ
4   1.000000e+09  MATMM-05         19.78   2000.0  PÇ
7   1.000000e+09  MATMM-01         10.11   2500.0  PÇ
9   1.000000e+09  MATMM-09         27.31     70.0  PÇ
0   1.000000e+09  MATMM-10         29.11    500.0  KG
2   1.000000e+09  MATMM-12         31.11  10000.0  KG
1   1.000000e+09  MATMM-12         31.11   1500.0  KG
3   1.000000e+09  MATMM-13         33.11    500.0  KG
4   1.000000e+09  MATMM-14         34.45    200.0  KG
19  1.000000e+09  MATMM-19         39.28   1000.0  MT
20  1.000000e+09  MATMM-20         40.72   2000.0  MT
24  1.000000e+09  MATMM-28         48.64    475.0  LT
25  1.000000e+09  MATMM-29         49.13   1900.0  LT
26  1.000000e+09  MATMM-30         50.11   2000.0  LT
27  1.000000e+09  MATMM-08         25.15   1000.0  PÇ
28  1.000000e+09  MATMM-08         25.15   1500.0  PÇ
29  1.000000e+09  MATMM-09         27.31   3000.0  PÇ
30  1.000000e+09  MATMM-31         10.90    100.0  PÇ

In [73]:
fazer_pedido.shape

(20, 5)

# <font color=orange>11) RC's que devem ter aditivo de valor</font>
***

In [74]:
rcs_2 = rcs_2[{'Req. Compra', 'Material', 'Qtde', 'UM', 'Contrato', 'ultimo_preco'}]
aditivo_valor = pd.concat([rcs_2])
aditivo_valor = aditivo_valor[['Req. Compra', 'Material', 'Contrato', 'ultimo_preco', 'Qtde', 'UM']]
aditivo_valor = aditivo_valor.sort_values(by='Req. Compra')
aditivo_valor

    Req. Compra  Material    Contrato  ultimo_preco     Qtde  UM
7  1.000000e+09  MATMM-17  4600000004         37.14  15000.0  KG
8  1.000000e+09  MATMM-18  4600000003         38.18  20000.0  KG
9  1.000000e+09  MATMM-21  4600000002         41.82    140.0  MT

In [75]:
aditivo_valor.shape

(3, 6)

# <font color=orange>12) RC's que tem contrato, mas que podem ter redução</font>
***

In [76]:
rcs_3 = rcs_3[{'Req. Compra', 'Material', 'Qtde', 'UM', 'Contrato', 'ultimo_preco'}]
negociar = pd.concat([rcs_3])
negociar = negociar[['Req. Compra', 'Material', 'Contrato', 'ultimo_preco', 'Qtde', 'UM']]
negociar = negociar.sort_values(by='Req. Compra')
negociar

     Req. Compra  Material    Contrato  ultimo_preco   Qtde  UM
10  1.000000e+09  MATMM-22  4600000001         42.74  500.0  MT

In [77]:
negociar.shape

(1, 6)

# <font color=orange>13) RC's que devem ser enviadas para cotação</font>
***

In [78]:
rcs_5 = rcs_5[{'Req. Compra', 'Material', 'Qtde', 'UM'}]
rcs_6 = rcs_6[{'Req. Compra', 'Material', 'Qtde', 'UM'}]
cotacao = pd.concat([rcs_5,rcs_6])
cotacao.head(3)

   Material Req. Compra  Qtde  UM
2  MATMM-03  1000000001  3600  PÇ
3  MATMM-03  1000000001  1500  PÇ
6  MATMM-04  1000000002   780  PÇ

In [79]:
df_condicoes = condicoes[{'Material', 'Grp Merc'}]
agrupando_rcs = pd.merge(cotacao, df_condicoes, on=['Material'], how='left')
agrupando_rcs.head(10)

   Material Req. Compra  Qtde  UM Grp Merc
0  MATMM-03  1000000001  3600  PÇ    GM-02
1  MATMM-03  1000000001  1500  PÇ    GM-02
2  MATMM-04  1000000002   780  PÇ    GM-02
3  MATMM-07  1000000004  5000  PÇ    GM-03
4  MATMM-23  1000000011   400  MT    GM-11
5  MATMM-32       1e+09  1000  PÇ      NaN
6  MATMM-33       1e+09  5000  PÇ      NaN

In [80]:
groupby1 = agrupando_rcs.groupby(["Grp Merc", "Material"])['Req. Compra'].count().reset_index()
groupby2 = agrupando_rcs.groupby(["Grp Merc", "Req. Compra"])['Material'].count().reset_index()
groupby3 = agrupando_rcs.groupby(["Grp Merc"])['Req. Compra'].count().reset_index()
agrupando = pd.merge(groupby1, groupby3, on=['Grp Merc'], how='left')
agrupando = pd.merge(agrupando, groupby2, on=['Grp Merc'], how='left')

def r(row):
    if row['Req. Compra_x'] == row['Req. Compra_y'] == row['Material_y']:
        val = 0
    else:
        val = 1
    return val  

agrupando["conc"] = agrupando.apply(r, axis=1)
agrupando= agrupando.rename(columns={'Material_x': 'Material'})
agrupando= agrupando.rename(columns={'Req. Compra_x': 'Req. Compra_Z'})

agrupando.head(3)

,Grp Merc,Material,Req. Compra_Z,Req. Compra_y,Req. Compra,Material_y,conc
0,GM-02,MATMM-03,2,3,1.000000e+09,2,1
1,GM-02,MATMM-03,2,3,1.000000e+09,1,1
2,GM-02,MATMM-04,1,3,1.000000e+09,2,1

In [81]:
#Selecionando apenas as RC's que não precisam ser agrupadas para cotação:

enviar_cotacao = agrupando

enviar_cotacao = enviar_cotacao.query('conc==0')
enviar_cotacao = enviar_cotacao.rename(columns={'Material_x': 'Material'})
enviar_cotacao = pd.merge(agrupando_rcs, enviar_cotacao, on=['Grp Merc'], how='left')
enviar_cotacao = enviar_cotacao.dropna()
enviar_cotacao = enviar_cotacao.rename(columns={'Req. Compra': 'OUT'})
enviar_cotacao = enviar_cotacao.rename(columns={'Req. Compra_x': 'Req. Compra'})
enviar_cotacao = enviar_cotacao.rename(columns={'Material_x': 'Material'})
rcs_7 = enviar_cotacao[{'Material', 'Req. Compra', 'Qtde', 'UM'}]

rcs_7

   Material Req. Compra  Qtde  UM
3  MATMM-07  1000000004  5000  PÇ
4  MATMM-23  1000000011   400  MT

In [82]:
#Consolidando as cotações:

consolidar = agrupando

consolidar = consolidar.query('conc==1')
consolidar = consolidar.rename(columns={'Material_x': 'Material'})
consolidar = consolidar[{'Grp Merc', 'Req. Compra'}]
consolidar = consolidar.drop_duplicates()

rcs_8 = consolidar
rcs_8["Consolidar"] = 1
rcs_8 = rcs_8[{'Grp Merc', 'Consolidar'}]
rcs_8 = rcs_8.drop_duplicates()
rcs_8 = pd.merge(agrupando_rcs, rcs_8, on=['Grp Merc'], how='left')
rcs_8 = rcs_8.dropna()
rcs_8 = rcs_8.sort_values('Grp Merc')
rcs_8 = rcs_8[{'Req. Compra', 'Material', 'Qtde', 'UM', 'Grp Merc'}]
rcs_8

  Req. Compra  Qtde  UM  Material Grp Merc
0  1000000001  3600  PÇ  MATMM-03    GM-02
1  1000000001  1500  PÇ  MATMM-03    GM-02
2  1000000002   780  PÇ  MATMM-04    GM-02

# <font color=orange>14) Arquivos finais</font>
***

In [83]:
# Arquivo que será gerado para Pedido Automático

fazer_pedido

     Req. Compra  Material  ultimo_preco     Qtde  UM
1   1.000000e+09  MATMM-02         12.12   2500.0  PÇ
0   1.000000e+09  MATMM-01         10.11   1000.0  PÇ
5   1.000000e+09  MATMM-06         21.07    580.0  PÇ
4   1.000000e+09  MATMM-05         19.78   2000.0  PÇ
7   1.000000e+09  MATMM-01         10.11   2500.0  PÇ
9   1.000000e+09  MATMM-09         27.31     70.0  PÇ
0   1.000000e+09  MATMM-10         29.11    500.0  KG
2   1.000000e+09  MATMM-12         31.11  10000.0  KG
1   1.000000e+09  MATMM-12         31.11   1500.0  KG
3   1.000000e+09  MATMM-13         33.11    500.0  KG
4   1.000000e+09  MATMM-14         34.45    200.0  KG
19  1.000000e+09  MATMM-19         39.28   1000.0  MT
20  1.000000e+09  MATMM-20         40.72   2000.0  MT
24  1.000000e+09  MATMM-28         48.64    475.0  LT
25  1.000000e+09  MATMM-29         49.13   1900.0  LT
26  1.000000e+09  MATMM-30         50.11   2000.0  LT
27  1.000000e+09  MATMM-08         25.15   1000.0  PÇ
28  1.000000e+09  MATMM-08         25.15   1500.0  PÇ
29  1.000000e+09  MATMM-09         27.31   3000.0  PÇ
30  1.000000e+09  MATMM-31         10.90    100.0  PÇ

In [84]:
pedidos = fazer_pedido.to_csv("fazer_pedido.csv")

In [85]:
# Arquivo que será gerado para Aditivo de valor

aditivo_valor

    Req. Compra  Material    Contrato  ultimo_preco     Qtde  UM
7  1.000000e+09  MATMM-17  4600000004         37.14  15000.0  KG
8  1.000000e+09  MATMM-18  4600000003         38.18  20000.0  KG
9  1.000000e+09  MATMM-21  4600000002         41.82    140.0  MT

In [86]:
aditivo = aditivo_valor.to_csv("aditivo_valor.csv")

In [87]:
# Arquivo que será gerado para itens de contrato que devem ser negociados

negociar

     Req. Compra  Material    Contrato  ultimo_preco   Qtde  UM
10  1.000000e+09  MATMM-22  4600000001         42.74  500.0  MT

In [88]:
negociacao = fazer_pedido.to_csv("negociar.csv")

In [89]:
# Arquivo que será gerado para itens que devem ser enviados para cotação sem consolidação e itens novos (sem historico de compras)
cotar = pd.concat([rcs_6,rcs_7])
cotar

    Material Req. Compra  Qtde  UM
36  MATMM-32       1e+09  1000  PÇ
37  MATMM-33       1e+09  5000  PÇ
3   MATMM-07  1000000004  5000  PÇ
4   MATMM-23  1000000011   400  MT

In [90]:
enviar_cotacao = cotar.to_csv("enviar_cotacao.csv")

In [91]:
# Arquivo que será gerado para itens que devem ser consolidados para cotações conjuntas

rcs_8

  Req. Compra  Qtde  UM  Material Grp Merc
0  1000000001  3600  PÇ  MATMM-03    GM-02
1  1000000001  1500  PÇ  MATMM-03    GM-02
2  1000000002   780  PÇ  MATMM-04    GM-02

In [92]:
consolidando = rcs_8.to_csv("consolidacao_rcs.csv")

# <font color=orange>15) Conferência e resumo</font>
***

In [93]:
total_rcs_processadas = pd.concat([fazer_pedido, aditivo_valor, negociar, cotar, rcs_8])
rcs_processadas = total_rcs_processadas['Req. Compra'].count()

In [94]:
total_requisicoes = requisicoes['Req. Compra'].count()
print("Quantidade de de RC's do dia = ", requisicoes['Req. Compra'].count())

Quantidade de de RC's do dia =  31

In [95]:
print("Quantidade de RC's retornadas pelo algoritmo =  ", total_rcs_processadas['Req. Compra'].count())

Quantidade de RC's retornadas pelo algoritmo =   31

In [96]:
if rcs_processadas == total_requisicoes:
    print('O algoritmo retornou a mesma quantidade de RCs que estava no sistema')
elif rcs_processadas <= total_requisicoes:
    print('O algoritmo retornou quantidade menor de RCs comparado ao que estava no sistema')
else:
    print('O algoritmo retornou quantidade maior de RCs comparado ao que estava no sistem. ERRO')

O algoritmo retornou a mesma quantidade de RCs que estava no sistema

In [97]:
print("Quantidade de RC's que devem ter pedidos criados automaticamente = ", fazer_pedido['Req. Compra'].count())

Quantidade de RC's que devem ter pedidos criados automaticamente =  20

In [98]:
print("Quantidade de RC's que devem ser submetidas à aditivo contratual = ", aditivo_valor['Req. Compra'].count())

Quantidade de RC's que devem ser submetidas à aditivo contratual =  3

In [99]:
print("Quantidade de RC's que tem contrato, mas que podem ter redução de preços = ", negociar['Req. Compra'].count())

Quantidade de RC's que tem contrato, mas que podem ter redução de preços =  1

In [100]:
print("Quantidade de RC's que devem ser enviadas para cotação sem necesidade de consolidação = ", cotar['Req. Compra'].count())

Quantidade de RC's que devem ser enviadas para cotação sem necesidade de consolidação =  4

In [101]:
print("Quantidade de RC's que devem ser consolidadas antes de envio à cotação =  ", rcs_8['Req. Compra'].count())

Quantidade de RC's que devem ser consolidadas antes de envio à cotação =   3